server:
  port: 8093
  servlet:
    context-path: /jxc

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_jxc?characterEncoding=utf8
    username: root
    password: 123456

  thymeleaf:
    cache: false
    
mybatis:
  type-aliases-package: com.fqt.project.entity